name: Deploy via FTP to sof-car.eu/api
on:
  push:
    branches: [main]

permissions:
  contents: write
  actions: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "Creating .env file..."
          cat > .env << 'EOF'
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          FLASK_ENV=production
          RATE_LIMIT_MAX_REQUESTS=3
          RATE_LIMIT_WINDOW_HOURS=1
          LOG_LEVEL=INFO
          EOF
          echo "Contents of .env file:"
          cat .env

      - name: Ensure tmp directory exists
        run: mkdir -p tmp

      - name: Trigger Passenger restart
        run: |
          echo "restart $(date)" > tmp/restart.txt

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: sof-car.eu
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /api/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
            **/.gitignore
            **/.env.example
            **/test_api.py
          dangerous-clean-slate: false
