name: Deploy via FTP to sof-car.eu/api
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: sof-car.eu
        username: ${{ secrets.FTP_USERNAME }}  
        password: ${{ secrets.FTP_PASSWORD }}  
        local-dir: ./
        server-dir: /api/  
        exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
            **/.gitignore
        dangerous-clean-slate: false

    - name: Ensure tmp directory exists
      run: mkdir -p tmp
    
    - name: Trigger Passenger restart
      run: |
        echo "restart $(date)" > tmp/restart.txt
